### ISSUE TITLE
Spread Operator

### ISSUE THREAD

**Issue by farishkash** [MikkelSandbag/codecademy-intensive-jammming#1]
https://github.com/MikkelSandbag/codecademy-intensive-jammming/blob/24fcd56f64c291e76ee3f2aa875fb6436d83d876/jammming/src/Components/App/App.js#L50

Not an issue, I rarely see the spread operator used or used properly in this submission.  Great job on this.

**Comment by MikkelSandbag** [comment]
Thanks! :)
